#!/bin/bash
#--------------------------------------------------------------------------
# @ Copyright (C) XX科技 - 保留版权 .
# @ Author: hollson <hollson@live.com>
# @ Date: 2019-12-01
# @ Describe：发布项目
#--------------------------------------------------------------------------

# 创建目录
mkdir -p ./release/bin ./release/conf ./release/conf


#打包文件
cp ./conf/config.ini ./release/conf
cp ./conf/config.ini ./release/conf


# 远程拷贝
scp -rp ./bin  root@39.104.x.x:/app/deeplink