// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo_v2.proto

package com.imrobot.proto;

public final class CommonShopProto {
  private CommonShopProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string talker = 1;</code>
     */
    boolean hasTalker();
    /**
     * <code>required string talker = 1;</code>
     */
    java.lang.String getTalker();
    /**
     * <code>required string talker = 1;</code>
     */
    com.google.protobuf.ByteString
        getTalkerBytes();

    /**
     * <code>required string content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     * 必传 1:文本消息. 2:图片URL 3：视频URL 4：语音URL 5：名片 6:文章 7:位置 8:红包
     * </pre>
     *
     * <code>required int32 msgType = 3;</code>
     */
    boolean hasMsgType();
    /**
     * <pre>
     * 必传 1:文本消息. 2:图片URL 3：视频URL 4：语音URL 5：名片 6:文章 7:位置 8:红包
     * </pre>
     *
     * <code>required int32 msgType = 3;</code>
     */
    int getMsgType();

    /**
     * <code>required string receiveWxId = 4;</code>
     */
    boolean hasReceiveWxId();
    /**
     * <code>required string receiveWxId = 4;</code>
     */
    java.lang.String getReceiveWxId();
    /**
     * <code>required string receiveWxId = 4;</code>
     */
    com.google.protobuf.ByteString
        getReceiveWxIdBytes();

    /**
     * <pre>
     * 视频第一帧图片地址
     * </pre>
     *
     * <code>optional string thImgVideo = 5;</code>
     */
    boolean hasThImgVideo();
    /**
     * <pre>
     * 视频第一帧图片地址
     * </pre>
     *
     * <code>optional string thImgVideo = 5;</code>
     */
    java.lang.String getThImgVideo();
    /**
     * <pre>
     * 视频第一帧图片地址
     * </pre>
     *
     * <code>optional string thImgVideo = 5;</code>
     */
    com.google.protobuf.ByteString
        getThImgVideoBytes();

    /**
     * <pre>
     * 视频时长，单位秒
     * </pre>
     *
     * <code>optional int32 videolength = 6;</code>
     */
    boolean hasVideolength();
    /**
     * <pre>
     * 视频时长，单位秒
     * </pre>
     *
     * <code>optional int32 videolength = 6;</code>
     */
    int getVideolength();

    /**
     * <code>required int64 createTime = 7;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>required int64 createTime = 7;</code>
     */
    long getCreateTime();
  }
  /**
   * <pre>
   * 消息实体
   * </pre>
   *
   * Protobuf type {@code ChatMsg}
   */
  public  static final class ChatMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatMsg)
      ChatMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMsg.newBuilder() to construct.
    private ChatMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMsg() {
      talker_ = "";
      content_ = "";
      receiveWxId_ = "";
      thImgVideo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              talker_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              content_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgType_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              receiveWxId_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              thImgVideo_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              videolength_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              createTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.imrobot.proto.CommonShopProto.internal_static_ChatMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.imrobot.proto.CommonShopProto.internal_static_ChatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.imrobot.proto.CommonShopProto.ChatMsg.class, com.imrobot.proto.CommonShopProto.ChatMsg.Builder.class);
    }

    private int bitField0_;
    public static final int TALKER_FIELD_NUMBER = 1;
    private volatile java.lang.Object talker_;
    /**
     * <code>required string talker = 1;</code>
     */
    public boolean hasTalker() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string talker = 1;</code>
     */
    public java.lang.String getTalker() {
      java.lang.Object ref = talker_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          talker_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string talker = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTalkerBytes() {
      java.lang.Object ref = talker_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        talker_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <code>required string content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTYPE_FIELD_NUMBER = 3;
    private int msgType_;
    /**
     * <pre>
     * 必传 1:文本消息. 2:图片URL 3：视频URL 4：语音URL 5：名片 6:文章 7:位置 8:红包
     * </pre>
     *
     * <code>required int32 msgType = 3;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 必传 1:文本消息. 2:图片URL 3：视频URL 4：语音URL 5：名片 6:文章 7:位置 8:红包
     * </pre>
     *
     * <code>required int32 msgType = 3;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int RECEIVEWXID_FIELD_NUMBER = 4;
    private volatile java.lang.Object receiveWxId_;
    /**
     * <code>required string receiveWxId = 4;</code>
     */
    public boolean hasReceiveWxId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string receiveWxId = 4;</code>
     */
    public java.lang.String getReceiveWxId() {
      java.lang.Object ref = receiveWxId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiveWxId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string receiveWxId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReceiveWxIdBytes() {
      java.lang.Object ref = receiveWxId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiveWxId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int THIMGVIDEO_FIELD_NUMBER = 5;
    private volatile java.lang.Object thImgVideo_;
    /**
     * <pre>
     * 视频第一帧图片地址
     * </pre>
     *
     * <code>optional string thImgVideo = 5;</code>
     */
    public boolean hasThImgVideo() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 视频第一帧图片地址
     * </pre>
     *
     * <code>optional string thImgVideo = 5;</code>
     */
    public java.lang.String getThImgVideo() {
      java.lang.Object ref = thImgVideo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          thImgVideo_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 视频第一帧图片地址
     * </pre>
     *
     * <code>optional string thImgVideo = 5;</code>
     */
    public com.google.protobuf.ByteString
        getThImgVideoBytes() {
      java.lang.Object ref = thImgVideo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        thImgVideo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VIDEOLENGTH_FIELD_NUMBER = 6;
    private int videolength_;
    /**
     * <pre>
     * 视频时长，单位秒
     * </pre>
     *
     * <code>optional int32 videolength = 6;</code>
     */
    public boolean hasVideolength() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 视频时长，单位秒
     * </pre>
     *
     * <code>optional int32 videolength = 6;</code>
     */
    public int getVideolength() {
      return videolength_;
    }

    public static final int CREATETIME_FIELD_NUMBER = 7;
    private long createTime_;
    /**
     * <code>required int64 createTime = 7;</code>
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required int64 createTime = 7;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTalker()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceiveWxId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, talker_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, msgType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, receiveWxId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, thImgVideo_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, videolength_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt64(7, createTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, talker_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, msgType_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, receiveWxId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, thImgVideo_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, videolength_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, createTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.imrobot.proto.CommonShopProto.ChatMsg)) {
        return super.equals(obj);
      }
      com.imrobot.proto.CommonShopProto.ChatMsg other = (com.imrobot.proto.CommonShopProto.ChatMsg) obj;

      if (hasTalker() != other.hasTalker()) return false;
      if (hasTalker()) {
        if (!getTalker()
            .equals(other.getTalker())) return false;
      }
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (hasMsgType() != other.hasMsgType()) return false;
      if (hasMsgType()) {
        if (getMsgType()
            != other.getMsgType()) return false;
      }
      if (hasReceiveWxId() != other.hasReceiveWxId()) return false;
      if (hasReceiveWxId()) {
        if (!getReceiveWxId()
            .equals(other.getReceiveWxId())) return false;
      }
      if (hasThImgVideo() != other.hasThImgVideo()) return false;
      if (hasThImgVideo()) {
        if (!getThImgVideo()
            .equals(other.getThImgVideo())) return false;
      }
      if (hasVideolength() != other.hasVideolength()) return false;
      if (hasVideolength()) {
        if (getVideolength()
            != other.getVideolength()) return false;
      }
      if (hasCreateTime() != other.hasCreateTime()) return false;
      if (hasCreateTime()) {
        if (getCreateTime()
            != other.getCreateTime()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTalker()) {
        hash = (37 * hash) + TALKER_FIELD_NUMBER;
        hash = (53 * hash) + getTalker().hashCode();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasMsgType()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMsgType();
      }
      if (hasReceiveWxId()) {
        hash = (37 * hash) + RECEIVEWXID_FIELD_NUMBER;
        hash = (53 * hash) + getReceiveWxId().hashCode();
      }
      if (hasThImgVideo()) {
        hash = (37 * hash) + THIMGVIDEO_FIELD_NUMBER;
        hash = (53 * hash) + getThImgVideo().hashCode();
      }
      if (hasVideolength()) {
        hash = (37 * hash) + VIDEOLENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getVideolength();
      }
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCreateTime());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.imrobot.proto.CommonShopProto.ChatMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.imrobot.proto.CommonShopProto.ChatMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.ChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.imrobot.proto.CommonShopProto.ChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.ChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.imrobot.proto.CommonShopProto.ChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.ChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.imrobot.proto.CommonShopProto.ChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.ChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.imrobot.proto.CommonShopProto.ChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.imrobot.proto.CommonShopProto.ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.imrobot.proto.CommonShopProto.ChatMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 消息实体
     * </pre>
     *
     * Protobuf type {@code ChatMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatMsg)
        com.imrobot.proto.CommonShopProto.ChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.imrobot.proto.CommonShopProto.internal_static_ChatMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.imrobot.proto.CommonShopProto.internal_static_ChatMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.imrobot.proto.CommonShopProto.ChatMsg.class, com.imrobot.proto.CommonShopProto.ChatMsg.Builder.class);
      }

      // Construct using com.imrobot.proto.CommonShopProto.ChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        talker_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        receiveWxId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        thImgVideo_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        videolength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.imrobot.proto.CommonShopProto.internal_static_ChatMsg_descriptor;
      }

      @java.lang.Override
      public com.imrobot.proto.CommonShopProto.ChatMsg getDefaultInstanceForType() {
        return com.imrobot.proto.CommonShopProto.ChatMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.imrobot.proto.CommonShopProto.ChatMsg build() {
        com.imrobot.proto.CommonShopProto.ChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.imrobot.proto.CommonShopProto.ChatMsg buildPartial() {
        com.imrobot.proto.CommonShopProto.ChatMsg result = new com.imrobot.proto.CommonShopProto.ChatMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.talker_ = talker_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.msgType_ = msgType_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.receiveWxId_ = receiveWxId_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.thImgVideo_ = thImgVideo_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.videolength_ = videolength_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.createTime_ = createTime_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.imrobot.proto.CommonShopProto.ChatMsg) {
          return mergeFrom((com.imrobot.proto.CommonShopProto.ChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.imrobot.proto.CommonShopProto.ChatMsg other) {
        if (other == com.imrobot.proto.CommonShopProto.ChatMsg.getDefaultInstance()) return this;
        if (other.hasTalker()) {
          bitField0_ |= 0x00000001;
          talker_ = other.talker_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000002;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasReceiveWxId()) {
          bitField0_ |= 0x00000008;
          receiveWxId_ = other.receiveWxId_;
          onChanged();
        }
        if (other.hasThImgVideo()) {
          bitField0_ |= 0x00000010;
          thImgVideo_ = other.thImgVideo_;
          onChanged();
        }
        if (other.hasVideolength()) {
          setVideolength(other.getVideolength());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTalker()) {
          return false;
        }
        if (!hasContent()) {
          return false;
        }
        if (!hasMsgType()) {
          return false;
        }
        if (!hasReceiveWxId()) {
          return false;
        }
        if (!hasCreateTime()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.imrobot.proto.CommonShopProto.ChatMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.imrobot.proto.CommonShopProto.ChatMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object talker_ = "";
      /**
       * <code>required string talker = 1;</code>
       */
      public boolean hasTalker() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string talker = 1;</code>
       */
      public java.lang.String getTalker() {
        java.lang.Object ref = talker_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            talker_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string talker = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTalkerBytes() {
        java.lang.Object ref = talker_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          talker_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string talker = 1;</code>
       */
      public Builder setTalker(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        talker_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string talker = 1;</code>
       */
      public Builder clearTalker() {
        bitField0_ = (bitField0_ & ~0x00000001);
        talker_ = getDefaultInstance().getTalker();
        onChanged();
        return this;
      }
      /**
       * <code>required string talker = 1;</code>
       */
      public Builder setTalkerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        talker_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 2;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       * 必传 1:文本消息. 2:图片URL 3：视频URL 4：语音URL 5：名片 6:文章 7:位置 8:红包
       * </pre>
       *
       * <code>required int32 msgType = 3;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * 必传 1:文本消息. 2:图片URL 3：视频URL 4：语音URL 5：名片 6:文章 7:位置 8:红包
       * </pre>
       *
       * <code>required int32 msgType = 3;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       * 必传 1:文本消息. 2:图片URL 3：视频URL 4：语音URL 5：名片 6:文章 7:位置 8:红包
       * </pre>
       *
       * <code>required int32 msgType = 3;</code>
       */
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000004;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 必传 1:文本消息. 2:图片URL 3：视频URL 4：语音URL 5：名片 6:文章 7:位置 8:红包
       * </pre>
       *
       * <code>required int32 msgType = 3;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object receiveWxId_ = "";
      /**
       * <code>required string receiveWxId = 4;</code>
       */
      public boolean hasReceiveWxId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string receiveWxId = 4;</code>
       */
      public java.lang.String getReceiveWxId() {
        java.lang.Object ref = receiveWxId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            receiveWxId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string receiveWxId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getReceiveWxIdBytes() {
        java.lang.Object ref = receiveWxId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiveWxId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string receiveWxId = 4;</code>
       */
      public Builder setReceiveWxId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        receiveWxId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string receiveWxId = 4;</code>
       */
      public Builder clearReceiveWxId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        receiveWxId_ = getDefaultInstance().getReceiveWxId();
        onChanged();
        return this;
      }
      /**
       * <code>required string receiveWxId = 4;</code>
       */
      public Builder setReceiveWxIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        receiveWxId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object thImgVideo_ = "";
      /**
       * <pre>
       * 视频第一帧图片地址
       * </pre>
       *
       * <code>optional string thImgVideo = 5;</code>
       */
      public boolean hasThImgVideo() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * 视频第一帧图片地址
       * </pre>
       *
       * <code>optional string thImgVideo = 5;</code>
       */
      public java.lang.String getThImgVideo() {
        java.lang.Object ref = thImgVideo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            thImgVideo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 视频第一帧图片地址
       * </pre>
       *
       * <code>optional string thImgVideo = 5;</code>
       */
      public com.google.protobuf.ByteString
          getThImgVideoBytes() {
        java.lang.Object ref = thImgVideo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          thImgVideo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 视频第一帧图片地址
       * </pre>
       *
       * <code>optional string thImgVideo = 5;</code>
       */
      public Builder setThImgVideo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        thImgVideo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 视频第一帧图片地址
       * </pre>
       *
       * <code>optional string thImgVideo = 5;</code>
       */
      public Builder clearThImgVideo() {
        bitField0_ = (bitField0_ & ~0x00000010);
        thImgVideo_ = getDefaultInstance().getThImgVideo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 视频第一帧图片地址
       * </pre>
       *
       * <code>optional string thImgVideo = 5;</code>
       */
      public Builder setThImgVideoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        thImgVideo_ = value;
        onChanged();
        return this;
      }

      private int videolength_ ;
      /**
       * <pre>
       * 视频时长，单位秒
       * </pre>
       *
       * <code>optional int32 videolength = 6;</code>
       */
      public boolean hasVideolength() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * 视频时长，单位秒
       * </pre>
       *
       * <code>optional int32 videolength = 6;</code>
       */
      public int getVideolength() {
        return videolength_;
      }
      /**
       * <pre>
       * 视频时长，单位秒
       * </pre>
       *
       * <code>optional int32 videolength = 6;</code>
       */
      public Builder setVideolength(int value) {
        bitField0_ |= 0x00000020;
        videolength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 视频时长，单位秒
       * </pre>
       *
       * <code>optional int32 videolength = 6;</code>
       */
      public Builder clearVideolength() {
        bitField0_ = (bitField0_ & ~0x00000020);
        videolength_ = 0;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>required int64 createTime = 7;</code>
       */
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required int64 createTime = 7;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>required int64 createTime = 7;</code>
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000040;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 createTime = 7;</code>
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        createTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatMsg)
    }

    // @@protoc_insertion_point(class_scope:ChatMsg)
    private static final com.imrobot.proto.CommonShopProto.ChatMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.imrobot.proto.CommonShopProto.ChatMsg();
    }

    public static com.imrobot.proto.CommonShopProto.ChatMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ChatMsg>
        PARSER = new com.google.protobuf.AbstractParser<ChatMsg>() {
      @java.lang.Override
      public ChatMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChatMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.imrobot.proto.CommonShopProto.ChatMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IdentityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Identity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 shopId = 1;</code>
     */
    boolean hasShopId();
    /**
     * <code>required int32 shopId = 1;</code>
     */
    int getShopId();

    /**
     * <code>required int32 userId = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <code>required string token = 3;</code>
     */
    boolean hasToken();
    /**
     * <code>required string token = 3;</code>
     */
    java.lang.String getToken();
    /**
     * <code>required string token = 3;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code Identity}
   */
  public  static final class Identity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Identity)
      IdentityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Identity.newBuilder() to construct.
    private Identity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Identity() {
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Identity();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Identity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              shopId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              token_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.imrobot.proto.CommonShopProto.internal_static_Identity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.imrobot.proto.CommonShopProto.internal_static_Identity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.imrobot.proto.CommonShopProto.Identity.class, com.imrobot.proto.CommonShopProto.Identity.Builder.class);
    }

    private int bitField0_;
    public static final int SHOPID_FIELD_NUMBER = 1;
    private int shopId_;
    /**
     * <code>required int32 shopId = 1;</code>
     */
    public boolean hasShopId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 shopId = 1;</code>
     */
    public int getShopId() {
      return shopId_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <code>required int32 userId = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object token_;
    /**
     * <code>required string token = 3;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string token = 3;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasShopId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, shopId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, userId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, shopId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.imrobot.proto.CommonShopProto.Identity)) {
        return super.equals(obj);
      }
      com.imrobot.proto.CommonShopProto.Identity other = (com.imrobot.proto.CommonShopProto.Identity) obj;

      if (hasShopId() != other.hasShopId()) return false;
      if (hasShopId()) {
        if (getShopId()
            != other.getShopId()) return false;
      }
      if (hasUserId() != other.hasUserId()) return false;
      if (hasUserId()) {
        if (getUserId()
            != other.getUserId()) return false;
      }
      if (hasToken() != other.hasToken()) return false;
      if (hasToken()) {
        if (!getToken()
            .equals(other.getToken())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasShopId()) {
        hash = (37 * hash) + SHOPID_FIELD_NUMBER;
        hash = (53 * hash) + getShopId();
      }
      if (hasUserId()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId();
      }
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.imrobot.proto.CommonShopProto.Identity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.imrobot.proto.CommonShopProto.Identity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.Identity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.imrobot.proto.CommonShopProto.Identity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.Identity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.imrobot.proto.CommonShopProto.Identity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.Identity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.imrobot.proto.CommonShopProto.Identity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.Identity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.imrobot.proto.CommonShopProto.Identity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.Identity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.imrobot.proto.CommonShopProto.Identity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.imrobot.proto.CommonShopProto.Identity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Identity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Identity)
        com.imrobot.proto.CommonShopProto.IdentityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.imrobot.proto.CommonShopProto.internal_static_Identity_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.imrobot.proto.CommonShopProto.internal_static_Identity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.imrobot.proto.CommonShopProto.Identity.class, com.imrobot.proto.CommonShopProto.Identity.Builder.class);
      }

      // Construct using com.imrobot.proto.CommonShopProto.Identity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        shopId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.imrobot.proto.CommonShopProto.internal_static_Identity_descriptor;
      }

      @java.lang.Override
      public com.imrobot.proto.CommonShopProto.Identity getDefaultInstanceForType() {
        return com.imrobot.proto.CommonShopProto.Identity.getDefaultInstance();
      }

      @java.lang.Override
      public com.imrobot.proto.CommonShopProto.Identity build() {
        com.imrobot.proto.CommonShopProto.Identity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.imrobot.proto.CommonShopProto.Identity buildPartial() {
        com.imrobot.proto.CommonShopProto.Identity result = new com.imrobot.proto.CommonShopProto.Identity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.shopId_ = shopId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userId_ = userId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.imrobot.proto.CommonShopProto.Identity) {
          return mergeFrom((com.imrobot.proto.CommonShopProto.Identity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.imrobot.proto.CommonShopProto.Identity other) {
        if (other == com.imrobot.proto.CommonShopProto.Identity.getDefaultInstance()) return this;
        if (other.hasShopId()) {
          setShopId(other.getShopId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasToken()) {
          bitField0_ |= 0x00000004;
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasShopId()) {
          return false;
        }
        if (!hasUserId()) {
          return false;
        }
        if (!hasToken()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.imrobot.proto.CommonShopProto.Identity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.imrobot.proto.CommonShopProto.Identity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int shopId_ ;
      /**
       * <code>required int32 shopId = 1;</code>
       */
      public boolean hasShopId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 shopId = 1;</code>
       */
      public int getShopId() {
        return shopId_;
      }
      /**
       * <code>required int32 shopId = 1;</code>
       */
      public Builder setShopId(int value) {
        bitField0_ |= 0x00000001;
        shopId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 shopId = 1;</code>
       */
      public Builder clearShopId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        shopId_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>required int32 userId = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>required string token = 3;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string token = 3;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string token = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string token = 3;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 3;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string token = 3;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Identity)
    }

    // @@protoc_insertion_point(class_scope:Identity)
    private static final com.imrobot.proto.CommonShopProto.Identity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.imrobot.proto.CommonShopProto.Identity();
    }

    public static com.imrobot.proto.CommonShopProto.Identity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Identity>
        PARSER = new com.google.protobuf.AbstractParser<Identity>() {
      @java.lang.Override
      public Identity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Identity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Identity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Identity> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.imrobot.proto.CommonShopProto.Identity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OperationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Operation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 必传. 具体业务指令 如发朋友圈，加好友，点赞等
     * </pre>
     *
     * <code>required int32 cmd = 1;</code>
     */
    boolean hasCmd();
    /**
     * <pre>
     * 必传. 具体业务指令 如发朋友圈，加好友，点赞等
     * </pre>
     *
     * <code>required int32 cmd = 1;</code>
     */
    int getCmd();

    /**
     * <pre>
     * 必传. 以JOSN格式编写具体数据
     * </pre>
     *
     * <code>required string data = 2;</code>
     */
    boolean hasData();
    /**
     * <pre>
     * 必传. 以JOSN格式编写具体数据
     * </pre>
     *
     * <code>required string data = 2;</code>
     */
    java.lang.String getData();
    /**
     * <pre>
     * 必传. 以JOSN格式编写具体数据
     * </pre>
     *
     * <code>required string data = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code Operation}
   */
  public  static final class Operation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Operation)
      OperationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Operation.newBuilder() to construct.
    private Operation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Operation() {
      data_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Operation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Operation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              cmd_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              data_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.imrobot.proto.CommonShopProto.internal_static_Operation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.imrobot.proto.CommonShopProto.internal_static_Operation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.imrobot.proto.CommonShopProto.Operation.class, com.imrobot.proto.CommonShopProto.Operation.Builder.class);
    }

    private int bitField0_;
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <pre>
     * 必传. 具体业务指令 如发朋友圈，加好友，点赞等
     * </pre>
     *
     * <code>required int32 cmd = 1;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 必传. 具体业务指令 如发朋友圈，加好友，点赞等
     * </pre>
     *
     * <code>required int32 cmd = 1;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object data_;
    /**
     * <pre>
     * 必传. 以JOSN格式编写具体数据
     * </pre>
     *
     * <code>required string data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 必传. 以JOSN格式编写具体数据
     * </pre>
     *
     * <code>required string data = 2;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 必传. 以JOSN格式编写具体数据
     * </pre>
     *
     * <code>required string data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.imrobot.proto.CommonShopProto.Operation)) {
        return super.equals(obj);
      }
      com.imrobot.proto.CommonShopProto.Operation other = (com.imrobot.proto.CommonShopProto.Operation) obj;

      if (hasCmd() != other.hasCmd()) return false;
      if (hasCmd()) {
        if (getCmd()
            != other.getCmd()) return false;
      }
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCmd()) {
        hash = (37 * hash) + CMD_FIELD_NUMBER;
        hash = (53 * hash) + getCmd();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.imrobot.proto.CommonShopProto.Operation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.imrobot.proto.CommonShopProto.Operation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.Operation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.imrobot.proto.CommonShopProto.Operation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.Operation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.imrobot.proto.CommonShopProto.Operation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.Operation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.imrobot.proto.CommonShopProto.Operation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.Operation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.imrobot.proto.CommonShopProto.Operation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.imrobot.proto.CommonShopProto.Operation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.imrobot.proto.CommonShopProto.Operation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.imrobot.proto.CommonShopProto.Operation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Operation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Operation)
        com.imrobot.proto.CommonShopProto.OperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.imrobot.proto.CommonShopProto.internal_static_Operation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.imrobot.proto.CommonShopProto.internal_static_Operation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.imrobot.proto.CommonShopProto.Operation.class, com.imrobot.proto.CommonShopProto.Operation.Builder.class);
      }

      // Construct using com.imrobot.proto.CommonShopProto.Operation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.imrobot.proto.CommonShopProto.internal_static_Operation_descriptor;
      }

      @java.lang.Override
      public com.imrobot.proto.CommonShopProto.Operation getDefaultInstanceForType() {
        return com.imrobot.proto.CommonShopProto.Operation.getDefaultInstance();
      }

      @java.lang.Override
      public com.imrobot.proto.CommonShopProto.Operation build() {
        com.imrobot.proto.CommonShopProto.Operation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.imrobot.proto.CommonShopProto.Operation buildPartial() {
        com.imrobot.proto.CommonShopProto.Operation result = new com.imrobot.proto.CommonShopProto.Operation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cmd_ = cmd_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.imrobot.proto.CommonShopProto.Operation) {
          return mergeFrom((com.imrobot.proto.CommonShopProto.Operation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.imrobot.proto.CommonShopProto.Operation other) {
        if (other == com.imrobot.proto.CommonShopProto.Operation.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000002;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCmd()) {
          return false;
        }
        if (!hasData()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.imrobot.proto.CommonShopProto.Operation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.imrobot.proto.CommonShopProto.Operation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int cmd_ ;
      /**
       * <pre>
       * 必传. 具体业务指令 如发朋友圈，加好友，点赞等
       * </pre>
       *
       * <code>required int32 cmd = 1;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 必传. 具体业务指令 如发朋友圈，加好友，点赞等
       * </pre>
       *
       * <code>required int32 cmd = 1;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <pre>
       * 必传. 具体业务指令 如发朋友圈，加好友，点赞等
       * </pre>
       *
       * <code>required int32 cmd = 1;</code>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 必传. 具体业务指令 如发朋友圈，加好友，点赞等
       * </pre>
       *
       * <code>required int32 cmd = 1;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <pre>
       * 必传. 以JOSN格式编写具体数据
       * </pre>
       *
       * <code>required string data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * 必传. 以JOSN格式编写具体数据
       * </pre>
       *
       * <code>required string data = 2;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 必传. 以JOSN格式编写具体数据
       * </pre>
       *
       * <code>required string data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 必传. 以JOSN格式编写具体数据
       * </pre>
       *
       * <code>required string data = 2;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 必传. 以JOSN格式编写具体数据
       * </pre>
       *
       * <code>required string data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 必传. 以JOSN格式编写具体数据
       * </pre>
       *
       * <code>required string data = 2;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Operation)
    }

    // @@protoc_insertion_point(class_scope:Operation)
    private static final com.imrobot.proto.CommonShopProto.Operation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.imrobot.proto.CommonShopProto.Operation();
    }

    public static com.imrobot.proto.CommonShopProto.Operation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Operation>
        PARSER = new com.google.protobuf.AbstractParser<Operation>() {
      @java.lang.Override
      public Operation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Operation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Operation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Operation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.imrobot.proto.CommonShopProto.Operation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Identity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Identity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Operation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Operation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rdemo_v2.proto\"\215\001\n\007ChatMsg\022\016\n\006talker\030\001 " +
      "\002(\t\022\017\n\007content\030\002 \002(\t\022\017\n\007msgType\030\003 \002(\005\022\023\n" +
      "\013receiveWxId\030\004 \002(\t\022\022\n\nthImgVideo\030\005 \001(\t\022\023" +
      "\n\013videolength\030\006 \001(\005\022\022\n\ncreateTime\030\007 \002(\003\"" +
      "9\n\010Identity\022\016\n\006shopId\030\001 \002(\005\022\016\n\006userId\030\002 " +
      "\002(\005\022\r\n\005token\030\003 \002(\t\"&\n\tOperation\022\013\n\003cmd\030\001" +
      " \002(\005\022\014\n\004data\030\002 \002(\tB*\n\021com.imrobot.protoB" +
      "\017CommonShopProtoZ\004.;pb"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ChatMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChatMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatMsg_descriptor,
        new java.lang.String[] { "Talker", "Content", "MsgType", "ReceiveWxId", "ThImgVideo", "Videolength", "CreateTime", });
    internal_static_Identity_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Identity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Identity_descriptor,
        new java.lang.String[] { "ShopId", "UserId", "Token", });
    internal_static_Operation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Operation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Operation_descriptor,
        new java.lang.String[] { "Cmd", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
