<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Pbs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 附加信息
 *
 * Generated from protobuf message <code>pbs.Append</code>
 */
class Append extends \Google\Protobuf\Internal\Message
{
    /**
     *学历信息
     *
     * Generated from protobuf field <code>repeated .pbs.Append.Educational educational = 1;</code>
     */
    private $educational;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pbs\Append\Educational[]|\Google\Protobuf\Internal\RepeatedField $educational
     *          学历信息
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     *学历信息
     *
     * Generated from protobuf field <code>repeated .pbs.Append.Educational educational = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEducational()
    {
        return $this->educational;
    }

    /**
     *学历信息
     *
     * Generated from protobuf field <code>repeated .pbs.Append.Educational educational = 1;</code>
     * @param \Pbs\Append\Educational[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEducational($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pbs\Append\Educational::class);
        $this->educational = $arr;

        return $this;
    }

}

