<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Pbs;

if (false) {
    /**
     * This class is deprecated. Use Pbs\Append\Educational instead.
     * @deprecated
     */
    class Append_Educational {}
}
class_exists(Append\Educational::class);
@trigger_error('Pbs\Append_Educational is deprecated and will be removed in the next major release. Use Pbs\Append\Educational instead', E_USER_DEPRECATED);

