<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace Pbs;

if (false) {
    /**
     * This class is deprecated. Use Pbs\PersonReply\Sex instead.
     * @deprecated
     */
    class PersonReply_Sex {}
}
class_exists(PersonReply\Sex::class);
@trigger_error('Pbs\PersonReply_Sex is deprecated and will be removed in the next major release. Use Pbs\PersonReply\Sex instead', E_USER_DEPRECATED);

