# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo_v3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo_v3.proto',
  package='pbs',
  syntax='proto3',
  serialized_options=_b('\n\024com.example.tutorialB\tPersonDto\252\002\010Pro.Demo'),
  serialized_pb=_b('\n\rdemo_v3.proto\x12\x03pbs\"\x1d\n\rPersonRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xd9\x01\n\x0bPersonReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07id_card\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12!\n\x03sex\x18\x04 \x01(\x0e\x32\x14.pbs.PersonReply.Sex\x12\x0f\n\x07married\x18\x05 \x01(\x08\x12\x0e\n\x06\x61mount\x18\x06 \x01(\x01\x12\x0f\n\x07\x61\x64\x64ress\x18\x07 \x03(\t\x12,\n\x0b\x65\x64ucational\x18\x08 \x01(\x0b\x32\x17.pbs.Append.Educational\"\x1b\n\x03Sex\x12\n\n\x06\x46\x45MALE\x10\x00\x12\x08\n\x04MALE\x10\x01\"l\n\x06\x41ppend\x12,\n\x0b\x65\x64ucational\x18\x01 \x03(\x0b\x32\x17.pbs.Append.Educational\x1a\x34\n\x0b\x45\x64ucational\x12\x12\n\nuniversity\x18\x01 \x01(\t\x12\x11\n\tspecialty\x18\x02 \x03(\t2H\n\x06Person\x12>\n\x14GetPersonInfoHandler\x12\x12.pbs.PersonRequest\x1a\x10.pbs.PersonReply\"\x00\x42,\n\x14\x63om.example.tutorialB\tPersonDto\xaa\x02\x08Pro.Demob\x06proto3')
)



_PERSONREPLY_SEX = _descriptor.EnumDescriptor(
  name='Sex',
  full_name='pbs.PersonReply.Sex',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MALE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=244,
  serialized_end=271,
)
_sym_db.RegisterEnumDescriptor(_PERSONREPLY_SEX)


_PERSONREQUEST = _descriptor.Descriptor(
  name='PersonRequest',
  full_name='pbs.PersonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pbs.PersonRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=51,
)


_PERSONREPLY = _descriptor.Descriptor(
  name='PersonReply',
  full_name='pbs.PersonReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pbs.PersonReply.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_card', full_name='pbs.PersonReply.id_card', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='pbs.PersonReply.age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sex', full_name='pbs.PersonReply.sex', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='married', full_name='pbs.PersonReply.married', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='pbs.PersonReply.amount', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='pbs.PersonReply.address', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='educational', full_name='pbs.PersonReply.educational', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PERSONREPLY_SEX,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=271,
)


_APPEND_EDUCATIONAL = _descriptor.Descriptor(
  name='Educational',
  full_name='pbs.Append.Educational',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='university', full_name='pbs.Append.Educational.university', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='specialty', full_name='pbs.Append.Educational.specialty', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=381,
)

_APPEND = _descriptor.Descriptor(
  name='Append',
  full_name='pbs.Append',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='educational', full_name='pbs.Append.educational', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_APPEND_EDUCATIONAL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=381,
)

_PERSONREPLY.fields_by_name['sex'].enum_type = _PERSONREPLY_SEX
_PERSONREPLY.fields_by_name['educational'].message_type = _APPEND_EDUCATIONAL
_PERSONREPLY_SEX.containing_type = _PERSONREPLY
_APPEND_EDUCATIONAL.containing_type = _APPEND
_APPEND.fields_by_name['educational'].message_type = _APPEND_EDUCATIONAL
DESCRIPTOR.message_types_by_name['PersonRequest'] = _PERSONREQUEST
DESCRIPTOR.message_types_by_name['PersonReply'] = _PERSONREPLY
DESCRIPTOR.message_types_by_name['Append'] = _APPEND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonRequest = _reflection.GeneratedProtocolMessageType('PersonRequest', (_message.Message,), {
  'DESCRIPTOR' : _PERSONREQUEST,
  '__module__' : 'demo_v3_pb2'
  # @@protoc_insertion_point(class_scope:pbs.PersonRequest)
  })
_sym_db.RegisterMessage(PersonRequest)

PersonReply = _reflection.GeneratedProtocolMessageType('PersonReply', (_message.Message,), {
  'DESCRIPTOR' : _PERSONREPLY,
  '__module__' : 'demo_v3_pb2'
  # @@protoc_insertion_point(class_scope:pbs.PersonReply)
  })
_sym_db.RegisterMessage(PersonReply)

Append = _reflection.GeneratedProtocolMessageType('Append', (_message.Message,), {

  'Educational' : _reflection.GeneratedProtocolMessageType('Educational', (_message.Message,), {
    'DESCRIPTOR' : _APPEND_EDUCATIONAL,
    '__module__' : 'demo_v3_pb2'
    # @@protoc_insertion_point(class_scope:pbs.Append.Educational)
    })
  ,
  'DESCRIPTOR' : _APPEND,
  '__module__' : 'demo_v3_pb2'
  # @@protoc_insertion_point(class_scope:pbs.Append)
  })
_sym_db.RegisterMessage(Append)
_sym_db.RegisterMessage(Append.Educational)


DESCRIPTOR._options = None

_PERSON = _descriptor.ServiceDescriptor(
  name='Person',
  full_name='pbs.Person',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=383,
  serialized_end=455,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPersonInfoHandler',
    full_name='pbs.Person.GetPersonInfoHandler',
    index=0,
    containing_service=None,
    input_type=_PERSONREQUEST,
    output_type=_PERSONREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERSON)

DESCRIPTOR.services_by_name['Person'] = _PERSON

# @@protoc_insertion_point(module_scope)
