// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo_v2.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 消息实体
type ChatMsg struct {
	Talker  *string `protobuf:"bytes,1,req,name=talker" json:"talker,omitempty"`
	Content *string `protobuf:"bytes,2,req,name=content" json:"content,omitempty"`
	// 必传 1:文本消息. 2:图片URL 3：视频URL 4：语音URL 5：名片 6:文章 7:位置 8:红包
	MsgType              *int32   `protobuf:"varint,3,req,name=msgType" json:"msgType,omitempty"`
	ReceiveWxId          *string  `protobuf:"bytes,4,req,name=receiveWxId" json:"receiveWxId,omitempty"`
	ThImgVideo           *string  `protobuf:"bytes,5,opt,name=thImgVideo" json:"thImgVideo,omitempty"`
	Videolength          *int32   `protobuf:"varint,6,opt,name=videolength" json:"videolength,omitempty"`
	CreateTime           *int64   `protobuf:"varint,7,req,name=createTime" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMsg) Reset()         { *m = ChatMsg{} }
func (m *ChatMsg) String() string { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()    {}
func (*ChatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4168b27b4e6048, []int{0}
}

func (m *ChatMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMsg.Unmarshal(m, b)
}
func (m *ChatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMsg.Marshal(b, m, deterministic)
}
func (m *ChatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMsg.Merge(m, src)
}
func (m *ChatMsg) XXX_Size() int {
	return xxx_messageInfo_ChatMsg.Size(m)
}
func (m *ChatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMsg proto.InternalMessageInfo

func (m *ChatMsg) GetTalker() string {
	if m != nil && m.Talker != nil {
		return *m.Talker
	}
	return ""
}

func (m *ChatMsg) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *ChatMsg) GetMsgType() int32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *ChatMsg) GetReceiveWxId() string {
	if m != nil && m.ReceiveWxId != nil {
		return *m.ReceiveWxId
	}
	return ""
}

func (m *ChatMsg) GetThImgVideo() string {
	if m != nil && m.ThImgVideo != nil {
		return *m.ThImgVideo
	}
	return ""
}

func (m *ChatMsg) GetVideolength() int32 {
	if m != nil && m.Videolength != nil {
		return *m.Videolength
	}
	return 0
}

func (m *ChatMsg) GetCreateTime() int64 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

type Identity struct {
	ShopId               *int32   `protobuf:"varint,1,req,name=shopId" json:"shopId,omitempty"`
	UserId               *int32   `protobuf:"varint,2,req,name=userId" json:"userId,omitempty"`
	Token                *string  `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4168b27b4e6048, []int{1}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetShopId() int32 {
	if m != nil && m.ShopId != nil {
		return *m.ShopId
	}
	return 0
}

func (m *Identity) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Identity) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type Operation struct {
	Cmd                  *int32   `protobuf:"varint,1,req,name=cmd" json:"cmd,omitempty"`
	Data                 *string  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4168b27b4e6048, []int{2}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetCmd() int32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *Operation) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatMsg)(nil), "ChatMsg")
	proto.RegisterType((*Identity)(nil), "Identity")
	proto.RegisterType((*Operation)(nil), "Operation")
}

func init() { proto.RegisterFile("demo_v2.proto", fileDescriptor_2e4168b27b4e6048) }

var fileDescriptor_2e4168b27b4e6048 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xda, 0xb4, 0x66, 0x44, 0xd4, 0x45, 0x64, 0x4f, 0x12, 0x7a, 0x0a, 0x1e, 0x0a,
	0x7a, 0xf5, 0xd6, 0x9e, 0x72, 0x10, 0xcb, 0x5a, 0x14, 0xbc, 0x48, 0x9a, 0x1d, 0x92, 0xd0, 0xee,
	0x4e, 0xd8, 0x8c, 0xc5, 0xfe, 0x54, 0xff, 0x8d, 0x6c, 0x9a, 0x40, 0x6e, 0xef, 0xfb, 0x96, 0x7d,
	0xf0, 0x06, 0xae, 0x34, 0x1a, 0xfa, 0x3e, 0x3e, 0x2f, 0x1b, 0x47, 0x4c, 0x8b, 0xbf, 0x00, 0xe6,
	0xeb, 0x2a, 0xe7, 0xd7, 0xb6, 0x14, 0xf7, 0x30, 0xe3, 0xfc, 0xb0, 0x47, 0x27, 0x83, 0x24, 0x4c,
	0x63, 0xd5, 0x93, 0x90, 0x30, 0x2f, 0xc8, 0x32, 0x5a, 0x96, 0x61, 0xf7, 0x30, 0xa0, 0x7f, 0x31,
	0x6d, 0xb9, 0x3d, 0x35, 0x28, 0x27, 0x49, 0x98, 0x46, 0x6a, 0x40, 0x91, 0xc0, 0xa5, 0xc3, 0x02,
	0xeb, 0x23, 0x7e, 0xfe, 0x66, 0x5a, 0x4e, 0xbb, 0x7f, 0x63, 0x25, 0x1e, 0x00, 0xb8, 0xca, 0x4c,
	0xf9, 0x51, 0x6b, 0x24, 0x19, 0x25, 0x41, 0x1a, 0xab, 0x91, 0xf1, 0x0d, 0x47, 0x1f, 0x0e, 0x68,
	0x4b, 0xae, 0xe4, 0x2c, 0x09, 0xd2, 0x48, 0x8d, 0x95, 0x6f, 0x28, 0x1c, 0xe6, 0x8c, 0xdb, 0xda,
	0xa0, 0x9c, 0x27, 0x61, 0x3a, 0x51, 0x23, 0xb3, 0xd8, 0xc0, 0x45, 0xa6, 0xd1, 0x72, 0xcd, 0x27,
	0xbf, 0xad, 0xad, 0xa8, 0xc9, 0x74, 0xb7, 0x2d, 0x52, 0x3d, 0x79, 0xff, 0xd3, 0xa2, 0xcb, 0x74,
	0x37, 0x2d, 0x52, 0x3d, 0x89, 0x3b, 0x88, 0x98, 0xf6, 0x68, 0xbb, 0x5d, 0xb1, 0x3a, 0xc3, 0xe2,
	0x09, 0xe2, 0xb7, 0x06, 0x5d, 0xce, 0x35, 0x59, 0x71, 0x03, 0x93, 0xc2, 0x0c, 0x7d, 0x3e, 0x0a,
	0x01, 0x53, 0x9d, 0x73, 0xde, 0x5f, 0xa9, 0xcb, 0xab, 0x47, 0xb8, 0x2d, 0xc8, 0x2c, 0x6b, 0xe3,
	0x68, 0x47, 0x7c, 0xbe, 0xfa, 0xea, 0x7a, 0x4d, 0xc6, 0x90, 0x7d, 0xaf, 0xa8, 0xd9, 0x78, 0xf1,
	0x35, 0x5d, 0xbe, 0x34, 0xbb, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x46, 0x9d, 0x1a, 0x03, 0x9c,
	0x01, 0x00, 0x00,
}
