// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: demo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pro.Demo {

  /// <summary>Holder for reflection information generated from demo.proto</summary>
  public static partial class DemoReflection {

    #region Descriptor
    /// <summary>File descriptor for demo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DemoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpkZW1vLnByb3RvEgNwYnMiHQoNUGVyc29uUmVxdWVzdBIMCgRuYW1lGAEg",
            "ASgJItkBCgtQZXJzb25SZXBseRIMCgRuYW1lGAEgASgJEg8KB2lkX2NhcmQY",
            "AiABKAkSCwoDYWdlGAMgASgFEiEKA3NleBgEIAEoDjIULnBicy5QZXJzb25S",
            "ZXBseS5TZXgSDwoHbWFycmllZBgFIAEoCBIOCgZhbW91bnQYBiABKAESDwoH",
            "YWRkcmVzcxgHIAMoCRIsCgtlZHVjYXRpb25hbBgIIAEoCzIXLnBicy5BcHBl",
            "bmQuRWR1Y2F0aW9uYWwiGwoDU2V4EgoKBkZFTUFMRRAAEggKBE1BTEUQASJs",
            "CgZBcHBlbmQSLAoLZWR1Y2F0aW9uYWwYASADKAsyFy5wYnMuQXBwZW5kLkVk",
            "dWNhdGlvbmFsGjQKC0VkdWNhdGlvbmFsEhIKCnVuaXZlcnNpdHkYASABKAkS",
            "EQoJc3BlY2lhbHR5GAIgAygJMkgKBlBlcnNvbhI+ChRHZXRQZXJzb25JbmZv",
            "SGFuZGxlchISLnBicy5QZXJzb25SZXF1ZXN0GhAucGJzLlBlcnNvblJlcGx5",
            "IgBCLAoUY29tLmV4YW1wbGUudHV0b3JpYWxCCVBlcnNvbkR0b6oCCFByby5E",
            "ZW1vYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pro.Demo.PersonRequest), global::Pro.Demo.PersonRequest.Parser, new[]{ "Name" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pro.Demo.PersonReply), global::Pro.Demo.PersonReply.Parser, new[]{ "Name", "IdCard", "Age", "Sex", "Married", "Amount", "Address", "Educational" }, null, new[]{ typeof(global::Pro.Demo.PersonReply.Types.Sex) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pro.Demo.Append), global::Pro.Demo.Append.Parser, new[]{ "Educational" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Pro.Demo.Append.Types.Educational), global::Pro.Demo.Append.Types.Educational.Parser, new[]{ "University", "Specialty" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 请求参数
  /// </summary>
  public sealed partial class PersonRequest : pb::IMessage<PersonRequest> {
    private static readonly pb::MessageParser<PersonRequest> _parser = new pb::MessageParser<PersonRequest>(() => new PersonRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PersonRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pro.Demo.DemoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonRequest(PersonRequest other) : this() {
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonRequest Clone() {
      return new PersonRequest(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PersonRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PersonRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PersonRequest other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 相应结果
  /// </summary>
  public sealed partial class PersonReply : pb::IMessage<PersonReply> {
    private static readonly pb::MessageParser<PersonReply> _parser = new pb::MessageParser<PersonReply>(() => new PersonReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PersonReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pro.Demo.DemoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonReply(PersonReply other) : this() {
      name_ = other.name_;
      idCard_ = other.idCard_;
      age_ = other.age_;
      sex_ = other.sex_;
      married_ = other.married_;
      amount_ = other.amount_;
      address_ = other.address_.Clone();
      educational_ = other.educational_ != null ? other.educational_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersonReply Clone() {
      return new PersonReply(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    ///姓名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_card" field.</summary>
    public const int IdCardFieldNumber = 2;
    private string idCard_ = "";
    /// <summary>
    ///身份证
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdCard {
      get { return idCard_; }
      set {
        idCard_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 3;
    private int age_;
    /// <summary>
    ///年龄
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    /// <summary>Field number for the "sex" field.</summary>
    public const int SexFieldNumber = 4;
    private global::Pro.Demo.PersonReply.Types.Sex sex_ = global::Pro.Demo.PersonReply.Types.Sex.Female;
    /// <summary>
    ///性别
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pro.Demo.PersonReply.Types.Sex Sex {
      get { return sex_; }
      set {
        sex_ = value;
      }
    }

    /// <summary>Field number for the "married" field.</summary>
    public const int MarriedFieldNumber = 5;
    private bool married_;
    /// <summary>
    ///是否已婚
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Married {
      get { return married_; }
      set {
        married_ = value;
      }
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 6;
    private double amount_;
    /// <summary>
    ///资产
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_address_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> address_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///地址
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Address {
      get { return address_; }
    }

    /// <summary>Field number for the "educational" field.</summary>
    public const int EducationalFieldNumber = 8;
    private global::Pro.Demo.Append.Types.Educational educational_;
    /// <summary>
    ///学历
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Pro.Demo.Append.Types.Educational Educational {
      get { return educational_; }
      set {
        educational_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PersonReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PersonReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (IdCard != other.IdCard) return false;
      if (Age != other.Age) return false;
      if (Sex != other.Sex) return false;
      if (Married != other.Married) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Amount, other.Amount)) return false;
      if(!address_.Equals(other.address_)) return false;
      if (!object.Equals(Educational, other.Educational)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (IdCard.Length != 0) hash ^= IdCard.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      if (Sex != global::Pro.Demo.PersonReply.Types.Sex.Female) hash ^= Sex.GetHashCode();
      if (Married != false) hash ^= Married.GetHashCode();
      if (Amount != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Amount);
      hash ^= address_.GetHashCode();
      if (educational_ != null) hash ^= Educational.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (IdCard.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdCard);
      }
      if (Age != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Age);
      }
      if (Sex != global::Pro.Demo.PersonReply.Types.Sex.Female) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Sex);
      }
      if (Married != false) {
        output.WriteRawTag(40);
        output.WriteBool(Married);
      }
      if (Amount != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Amount);
      }
      address_.WriteTo(output, _repeated_address_codec);
      if (educational_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Educational);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (IdCard.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdCard);
      }
      if (Age != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Age);
      }
      if (Sex != global::Pro.Demo.PersonReply.Types.Sex.Female) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Sex);
      }
      if (Married != false) {
        size += 1 + 1;
      }
      if (Amount != 0D) {
        size += 1 + 8;
      }
      size += address_.CalculateSize(_repeated_address_codec);
      if (educational_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Educational);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PersonReply other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.IdCard.Length != 0) {
        IdCard = other.IdCard;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      if (other.Sex != global::Pro.Demo.PersonReply.Types.Sex.Female) {
        Sex = other.Sex;
      }
      if (other.Married != false) {
        Married = other.Married;
      }
      if (other.Amount != 0D) {
        Amount = other.Amount;
      }
      address_.Add(other.address_);
      if (other.educational_ != null) {
        if (educational_ == null) {
          Educational = new global::Pro.Demo.Append.Types.Educational();
        }
        Educational.MergeFrom(other.Educational);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            IdCard = input.ReadString();
            break;
          }
          case 24: {
            Age = input.ReadInt32();
            break;
          }
          case 32: {
            Sex = (global::Pro.Demo.PersonReply.Types.Sex) input.ReadEnum();
            break;
          }
          case 40: {
            Married = input.ReadBool();
            break;
          }
          case 49: {
            Amount = input.ReadDouble();
            break;
          }
          case 58: {
            address_.AddEntriesFrom(input, _repeated_address_codec);
            break;
          }
          case 66: {
            if (educational_ == null) {
              Educational = new global::Pro.Demo.Append.Types.Educational();
            }
            input.ReadMessage(Educational);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the PersonReply message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Sex {
        [pbr::OriginalName("FEMALE")] Female = 0,
        [pbr::OriginalName("MALE")] Male = 1,
      }

    }
    #endregion

  }

  /// <summary>
  /// 附加信息
  /// </summary>
  public sealed partial class Append : pb::IMessage<Append> {
    private static readonly pb::MessageParser<Append> _parser = new pb::MessageParser<Append>(() => new Append());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Append> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pro.Demo.DemoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Append() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Append(Append other) : this() {
      educational_ = other.educational_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Append Clone() {
      return new Append(this);
    }

    /// <summary>Field number for the "educational" field.</summary>
    public const int EducationalFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Pro.Demo.Append.Types.Educational> _repeated_educational_codec
        = pb::FieldCodec.ForMessage(10, global::Pro.Demo.Append.Types.Educational.Parser);
    private readonly pbc::RepeatedField<global::Pro.Demo.Append.Types.Educational> educational_ = new pbc::RepeatedField<global::Pro.Demo.Append.Types.Educational>();
    /// <summary>
    ///学历信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Pro.Demo.Append.Types.Educational> Educational {
      get { return educational_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Append);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Append other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!educational_.Equals(other.educational_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= educational_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      educational_.WriteTo(output, _repeated_educational_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += educational_.CalculateSize(_repeated_educational_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Append other) {
      if (other == null) {
        return;
      }
      educational_.Add(other.educational_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            educational_.AddEntriesFrom(input, _repeated_educational_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Append message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Educational : pb::IMessage<Educational> {
        private static readonly pb::MessageParser<Educational> _parser = new pb::MessageParser<Educational>(() => new Educational());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Educational> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Pro.Demo.Append.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Educational() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Educational(Educational other) : this() {
          university_ = other.university_;
          specialty_ = other.specialty_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Educational Clone() {
          return new Educational(this);
        }

        /// <summary>Field number for the "university" field.</summary>
        public const int UniversityFieldNumber = 1;
        private string university_ = "";
        /// <summary>
        ///毕业学校
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string University {
          get { return university_; }
          set {
            university_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "specialty" field.</summary>
        public const int SpecialtyFieldNumber = 2;
        private static readonly pb::FieldCodec<string> _repeated_specialty_codec
            = pb::FieldCodec.ForString(18);
        private readonly pbc::RepeatedField<string> specialty_ = new pbc::RepeatedField<string>();
        /// <summary>
        ///专业
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<string> Specialty {
          get { return specialty_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Educational);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Educational other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (University != other.University) return false;
          if(!specialty_.Equals(other.specialty_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (University.Length != 0) hash ^= University.GetHashCode();
          hash ^= specialty_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (University.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(University);
          }
          specialty_.WriteTo(output, _repeated_specialty_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (University.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(University);
          }
          size += specialty_.CalculateSize(_repeated_specialty_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Educational other) {
          if (other == null) {
            return;
          }
          if (other.University.Length != 0) {
            University = other.University;
          }
          specialty_.Add(other.specialty_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                University = input.ReadString();
                break;
              }
              case 18: {
                specialty_.AddEntriesFrom(input, _repeated_specialty_codec);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
